import re
import sys
import json
import os
from datetime import datetime

def extract_intel(logfile):
    if not os.path.exists(logfile):
        return None

    with open(logfile, 'r') as f:
        content = f.read()

    patterns = {
        "Emails": r"[\w.+-]+@[\w.-]+\.\w+",
        "Onions": r"\b[a-z2-7]{56}\.onion\b",
        "Telegram": r"(?:https?://t\.me/|@)([A-Za-z0-9_]{5,32})",
        "Wallets (BTC/ETH)": r"\b(?:bc1[a-z0-9]{25,87}|[13][a-km-zA-HJ-NP-Z1-9]{25,34}|0x[a-fA-F0-9]{40})\b",
        "IPv4 Addresses": r"\b(?:\d{1,3}\.){3}\d{1,3}\b",
        "Domains/URLs": r"\b(?:[a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}\b",
        "AWS Keys": r"(?i)(AKIA[0-9A-Z]{16})",
        "GitHub Tokens": r"(ghp_[a-zA-Z0-9]{36})",
        "Private Keys": r"-----BEGIN (?:RSA|OPENSSH|EC|PGP) PRIVATE KEY-----",
        "Secrets/API Keys": r"(?i)(api[_-]?key|password|secret|access[_-]?token|bearer|id[_-]?secret)\s*[:=]\s*['\"]?([a-zA-Z0-9_-]{16,})['\"]?"
    }

    intel = {}
    for label, pattern in patterns.items():
        matches = sorted(list(set(re.findall(pattern, content))))
        if matches:
            # For secrets, we might want to store the whole match or groups
            if label == "Secrets/API Keys":
                intel[label] = [f"{m[0]}: {m[1]}" for m in matches]
            else:
                intel[label] = matches
    return intel

def generate_html(target, intel, htmlfile):
    html_template = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LOL War-Room: {target}</title>
    <style>
        :root {{
            --bg-color: #050505;
            --card-bg: #0f0f0f;
            --neon-blue: #00f2ff;
            --neon-pink: #ff00ff;
            --text-color: #e0e0e0;
        }}
        body {{ 
            background-color: var(--bg-color); 
            color: var(--text-color); 
            font-family: 'Segoe UI', 'Courier New', monospace; 
            margin: 0; 
            padding: 40px; 
            line-height: 1.6;
        }}
        .header {{ 
            border: 2px solid var(--neon-pink); 
            padding: 30px; 
            text-shadow: 0 0 15px var(--neon-pink); 
            margin-bottom: 30px; 
            background: rgba(255, 0, 255, 0.05);
            border-radius: 8px;
        }}
        h1 {{ color: var(--neon-pink); margin: 0; font-size: 2.5em; letter-spacing: 5px; }}
        .target-info {{ color: var(--neon-blue); font-size: 1.1em; margin-top: 10px; }}
        .grid {{ 
            display: grid; 
            grid-template-columns: repeat(auto-fill, minmax(350px, 1fr)); 
            gap: 25px; 
        }}
        .card {{ 
            background: var(--card-bg); 
            border: 1px solid #222;
            border-left: 5px solid var(--neon-blue); 
            padding: 20px; 
            border-radius: 4px;
            box-shadow: 0 10px 30px rgba(0,0,0,0.5);
            transition: transform 0.2s;
        }}
        .card:hover {{
            transform: translateY(-5px);
            border-color: var(--neon-blue);
        }}
        .label {{ 
            color: var(--neon-pink); 
            font-weight: bold; 
            text-transform: uppercase; 
            margin-bottom: 15px; 
            display: block; 
            font-size: 0.9em;
            letter-spacing: 2px;
            border-bottom: 1px solid #333;
            padding-bottom: 5px;
        }}
        .value {{ 
            color: var(--neon-blue); 
            word-wrap: break-word; 
            font-family: 'Courier New', monospace;
            font-size: 0.95em;
        }}
        .value a {{
            color: var(--neon-blue);
            text-decoration: none;
        }}
        .value a:hover {{
            text-decoration: underline;
        }}
        .footer {{ 
            margin-top: 60px; 
            font-size: 0.8em; 
            color: #555; 
            border-top: 1px solid #222; 
            padding-top: 20px; 
            text-align: center;
        }}
        .stats {{
            margin-bottom: 30px;
            display: flex;
            gap: 20px;
        }}
        .stat-item {{
            background: #111;
            padding: 10px 20px;
            border-radius: 20px;
            border: 1px solid #333;
            font-size: 0.85em;
        }}
        .stat-item b {{ color: var(--neon-pink); }}
    </style>
</head>
<body>
    <div class="header">
        <h1>L O L  //  W A R - R O O M</h1>
        <div class="target-info">TARGET: {target} | SESSION DATE: {date}</div>
    </div>
    
    <div class="stats">
        {stats}
    </div>

    <div class="grid">
        {cards}
    </div>
    
    <div class="footer">
        Generated by <b>LOL Potency Edition</b> // Extreme Reconnaissance & Intelligence Platform<br>
        &copy; 2026 sinXne0 Cyber-Infrastructure
    </div>
</body>
</html>
"""

    cards = ""
    stat_items = []
    for label, items in intel.items():
        stat_items.append(f'<div class="stat-item"><b>{len(items)}</b> {label}</div>')
        
        formatted_items = []
        for i in items[:50]:
            # Basic auto-link
            if label in ["Domains/URLs", "Onions"] or i.startswith("http"):
                formatted_items.append(f'• <a href="{i if "://" in i else "http://"+i}" target="_blank">{i}</a>')
            else:
                formatted_items.append(f'• {i}')
        
        items_html = "<br>".join(formatted_items)
        if len(items) > 50:
            items_html += f"<br><i>... and {len(items)-50} more findings in JSON report</i>"
            
        cards += f'<div class="card"><span class="label">{label}</span><div class="value">{items_html}</div></div>'

    stats_html = "\n".join(stat_items)
    
    with open(htmlfile, 'w') as f:
        f.write(html_template.format(
            target=target,
            date=datetime.now().strftime("%Y-%m-%d %H:%M"),
            cards=cards,
            stats=stats_html
        ))

if __name__ == "__main__":
    if len(sys.argv) < 4:
        print("Usage: dashboard.py <logfile> <jsonfile> <htmlfile>")
        sys.exit(1)

    logfile, jsonfile, htmlfile = sys.argv[1], sys.argv[2], sys.argv[3]
    target_name = os.path.basename(logfile).replace("lol_report_", "").replace(".txt", "")
    
    intel_data = extract_intel(logfile)
    if intel_data:
        with open(jsonfile, 'w') as f:
            json.dump(intel_data, f, indent=4)
        generate_html(target_name, intel_data, htmlfile)
        print(f"Extraction complete. Dashboard: {htmlfile}")
